lhcbpr2grid_web/lhcbpr2grid_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("tasks/", include("tasks.urls")),
    path('admin/', admin.site.urls),
]

lhcbpr2grid_web/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
        # ex: /tasks/
        path("", views.index, name="index"),
        # ex: /tasks/5/
        path("<int:task_id>/", views.detail, name="detail"),
    ]

lhcbpr2grid_web/tasks/models.py
from django.db import models

# ProductionTask is a single submission to Ganga of either a Job or Task
class Task(models.Model):
    task_name = models.CharField(max_length=500)
    task_submit_date = models.DateTimeField("submit date")
    curr_status = models.CharField(max_length=100)
    ganga_task_id = models.IntegerField(default=-1)
    status_info = models.CharField(max_length=3000)

    def __str__(self):
        ret_str = self.task_name + " ({})".format(self.curr_status)
        return ret_str
    
class Stage(models.Model):
    stage_name = models.CharField(max_length=500)
    stage_submit_date = models.DateTimeField("submit date")
    curr_status = models.CharField(max_length=100)
    ganga_job_id = models.IntegerField(default=-1)
    ganga_transform_id = models.IntegerField(default=-1)
    num_dirac_jobs = models.IntegerField(default=-1)
    task_parent = models.ForeignKey(Task, on_delete=models.CASCADE)
    status_info  = models.CharField(max_length=3000)

    def __str__(self):
        ret_str = self.stage_name + " ({})".format(self.curr_status)
        return ret_str

class DiracJob(models.Model):
    dirac_id = models.IntegerField(default=-1)
    job_status = models.CharField(max_length=100)
    stage_parent = models.ForeignKey(Stage, on_delete=models.CASCADE)

    def __str__(self):
        ret_str = int(self.dirac_id) + " ({})".format(self.job_status)
        return ret_str

lhcbpr2grid_web/tasks/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Task, Stage, DiracJob
from django.shortcuts import render

# Create your views here.
def index(request):
    latest_task_list = Task.objects.order_by("-task_submit_date")[:5]
    
    context = {"latest_task_list": latest_task_list}
    return render(request, "tasks/index.html", context)
    
def detail(request, task_id):
    try:
        task = Task.objects.get(pk=task_id)
    except Task.DoesNotExist:
        raise Http404("Task does not exist")
    return render(request, "tasks/detail.html", {"task": task})


    

lhcbpr2grid_web/tasks/templates/tasks/detail.html
<!-- Latest compiled and minified CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script> 


<h1>{{ task.task_name }}</h1>
<ul>
  <li>Submitted: {{task.task_submit_date}}</li>
  <li>Current Status: {{task.curr_status}}</li>
  <li>Info: {{task.status_info}}</li>
</ul>

<br><br>
<h2>STAGES:  </h2>
<div class="accordion" id="accordionExample">
  {% for stage in task.stage_set.all %}
  <div class="accordion-item">
    <h2 class="accordion-header" id="heading{{ forloop.counter0 }}">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter0 }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter0 }}">
	{{ stage.stage_name }} &nbsp; &nbsp; &nbsp; 
	{% if stage.curr_status == "failed" %}
	<font color="red"> {{ stage.curr_status }} </font>
	{% elif stage.curr_status == "submitted" %}
	<font color="orange"> {{ stage.curr_status }} </font>
	{% elif stage.curr_status == "running" %}
	<font color="green"> {{ stage.curr_status }} </font>
	{% elif stage.curr_status == "completed" %}
	<font color="blue"> {{ stage.curr_status }} </font>
	{% else %}
	 {{ stage.curr_status }}
	{% endif %}

	&nbsp; &nbsp; &nbsp; {{ stage.num_dirac_jobs }} DIRAC JOBS.
      </button>
    </h2>
    <div id="collapse{{ forloop.counter0 }}" class="accordion-collapse collapse" aria-labelledby="heading{{ forloop.counter0 }}" data-bs-parent="#StageAccordion">
      <div class="accordion-body">
	<!-- <pre>{{ stage.status_info }}</pre> -->
	{% for diracid in stage.diracjob_set.all %}
	Job {{ diracid.dirac_id }}
	{% if diracid.job_status == "failed" %}
	<font color="red"> {{ diracid.job_status }} </font>
	{% elif diracid.job_status == "submitted" %}
	<font color="orange"> {{ diracid.job_status }} </font>
	{% elif diracid.job_status == "running" %}
	<font color="green"> {{ diracid.job_status }} </font>
	{% elif diracid.job_status == "completed" %}
	<font color="blue"> {{ diracid.job_status }} </font>
	{% else %}
	 {{ diracid.job_status }}
	{% endif %}
	<br>
	{% endfor %}
	<br><br>
	<pre>
	  {{ stage.status_info }}
	  </pre>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

lhcbpr2grid_web/tasks/templates/tasks/index.html
{% load static %}
<!-- Latest compiled and minified CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script> 

<link rel="stylesheet" href="{% static 'tasks/style.css' %}">

<div class="container">
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-4">LHCbPR2Grid Jobs</span>
    </a>

    <ul class="nav nav-pills">
      <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
<!--      <li class="nav-item"><a href="#" class="nav-link">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link">About</a></li> -->
    </ul>
  </header>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Task Name</th>
      <th>Submission Time</th>
      <th>Status</th>
<!--      <th>Info</th> -->
      <th>Stage Name</th>
      <th>Stage Status</th>
      <th>Num DIRAC Jobs</th>
    </tr>
  </thead>
  <tbody>

    
{% if latest_task_list %}
{% for task in latest_task_list %}
<tr>
  <td rowspan="{{ task.stage_set.all|length }}"><a href="{% url 'tasks:detail' task.id %}">{{ task.task_name }}</a></td>
  <td rowspan="{{ task.stage_set.all|length }}">{{ task.task_submit_date }}</td>
  {% if task.curr_status == "task failed" or task.curr_status == "jobs failed" %}
  <td rowspan="{{ task.stage_set.all|length }}" style="color: red;">{{ task.curr_status }}</td>
  {% elif task.curr_status == "task submitted" or task.curr_status == "jobs complete"%}
  <td rowspan="{{ task.stage_set.all|length }}" style="color: orange;">{{ task.curr_status }}</td>
  {% elif task.curr_status == "jobs running" %}
  <td rowspan="{{ task.stage_set.all|length }}" style="color: green;">{{ task.curr_status }}</td>
  {% else %}
  <td rowspan="">{{ task.curr_status }}</td>
  {% endif %}
  <!--  <td>{{ task.status_info }}</td> -->
  {% for stage in task.stage_set.all %}
    <td>{{ stage.stage_name }}</td>
    {% if stage.curr_status == "failed" %}
    <td style="color: red;">{{ stage.curr_status }}</td>
    {% elif stage.curr_status == "submitted" %}
    <td style="color: orange;">{{ stage.curr_status }}</td>
    {% elif stage.curr_status == "running" %}
    <td style="color: green;">{{ stage.curr_status }}</td>
    {% elif stage.curr_status == "completed" %}
    <td style="color: blue;">{{ stage.curr_status }}</td>
    {% else %}
    <td>{{ stage.curr_status }}</td>
    {% endif %}
    <td>{{ stage.num_dirac_jobs }}</td>
</tr><tr>
   {% endfor %}
</tr>
{% endfor %}
  </tbody>
</table>
{% else %}
  </tbody>
</table>
<p>No tasks are available.</p>
{% endif %}